services:
  flask:
    image: flask-projeto-1
    build: ./python
    ports:
      - 5000:5000
    volumes:
      -./python/app:/app

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senhasegura123